# Exrecise 1

In [1]:
import math


### Chapter 1

9.

In [5]:
print(math.factorial(6))

720


10.

In [14]:
count = 0
for year in range(1500,2011):
    if (year % 4 == 0):
        if (year % 100 == 0):
            if (year % 400 == 0):
                count = count + 1
        else:
            count = count + 1
print(count)  

124


11.

13.

In [6]:
x_values = [math.pi, 2 * math.pi, 4 * math.pi, 6 * math.pi]

results = [(x, math.sin(x)**2 + math.cos(x)**2) for x in x_values]

for x, result in results:
    print(f"x = {x}: sin^2(x) + cos^2(x) = {result:.15f}")

x = 3.141592653589793: sin^2(x) + cos^2(x) = 1.000000000000000
x = 6.283185307179586: sin^2(x) + cos^2(x) = 1.000000000000000
x = 12.566370614359172: sin^2(x) + cos^2(x) = 1.000000000000000
x = 18.84955592153876: sin^2(x) + cos^2(x) = 1.000000000000000


14.

In [7]:
angle_degrees = 87
angle_radians = math.radians(angle_degrees)

sin_value = math.sin(angle_radians)
print(f"sin(87°) = {sin_value:.15f}")

sin(87°) = 0.998629534754574


19.

In [9]:
values = [True, False]
for P in values:
    for Q in values:
        result = (P and Q) or (P and (not Q))
        print(f"P = {P}, Q = {Q}, (P AND Q) OR (P AND (NOT Q)) = {result}")
        if not result:
            print(f"The expression is false when P = {P} and Q = {Q}")

P = True, Q = True, (P AND Q) OR (P AND (NOT Q)) = True
P = True, Q = False, (P AND Q) OR (P AND (NOT Q)) = True
P = False, Q = True, (P AND Q) OR (P AND (NOT Q)) = False
The expression is false when P = False and Q = True
P = False, Q = False, (P AND Q) OR (P AND (NOT Q)) = False
The expression is false when P = False and Q = False


22.

Chapter 2

1.

In [11]:
s1 = 'HELLO'
s2 = 'hello'

are_equal = s1 == s2
are_equal_lowercase = s1.lower() == s2
are_equal_uppercase = s1 == s2.upper()

s1, s2, are_equal, are_equal_lowercase, are_equal_uppercase

('HELLO', 'hello', False, True, True)

2.

In [12]:
S = '123'
N = float(S)

type_S = type(S)
type_N = type(N)

S, N, type_S, type_N

('123', 123.0, str, float)

3.

In [13]:
s1 = 'HELLO'
s2 = 'hello'
print(s1 == s2)
print(s1.lower() == s2)
print(s1 == s2.upper())

False
True
True


4.

In [14]:
word1 = 'Engineering'
length1 = len(word1)

word2 = 'Book'
length2 = len(word2)
print(f"The word '{word1}' has {length1} letters.")
print(f"The word '{word2}' has {length2} letters.")


The word 'Engineering' has 11 letters.
The word 'Book' has 4 letters.


5.

In [15]:
substring = 'Python'
full_string = 'Python is great!'

is_in_string = substring in full_string
print(is_in_string)

True


6.

In [16]:
sentence = 'Python is great!'
words = sentence.split()
last_word = words[-1]
print(last_word)

great!


7.

In [17]:
list_a = [1, 8, 9, 15]
list_a.insert(1, 2)
list_a.append(4)
print(list_a)

[1, 2, 8, 9, 15, 4]


8.

In [18]:
list_a = [1, 2, 8, 9, 15, 4]
list_a.sort()
print(list_a)

[1, 2, 4, 8, 9, 15]


17.

In [2]:
import numpy

In [22]:
array = numpy.linspace(-10, 10, 100)
print(array)

[-10.          -9.7979798   -9.5959596   -9.39393939  -9.19191919
  -8.98989899  -8.78787879  -8.58585859  -8.38383838  -8.18181818
  -7.97979798  -7.77777778  -7.57575758  -7.37373737  -7.17171717
  -6.96969697  -6.76767677  -6.56565657  -6.36363636  -6.16161616
  -5.95959596  -5.75757576  -5.55555556  -5.35353535  -5.15151515
  -4.94949495  -4.74747475  -4.54545455  -4.34343434  -4.14141414
  -3.93939394  -3.73737374  -3.53535354  -3.33333333  -3.13131313
  -2.92929293  -2.72727273  -2.52525253  -2.32323232  -2.12121212
  -1.91919192  -1.71717172  -1.51515152  -1.31313131  -1.11111111
  -0.90909091  -0.70707071  -0.50505051  -0.3030303   -0.1010101
   0.1010101    0.3030303    0.50505051   0.70707071   0.90909091
   1.11111111   1.31313131   1.51515152   1.71717172   1.91919192
   2.12121212   2.32323232   2.52525253   2.72727273   2.92929293
   3.13131313   3.33333333   3.53535354   3.73737374   3.93939394
   4.14141414   4.34343434   4.54545455   4.74747475   4.94949495
   5.151515

18.

In [3]:
array_a = numpy.array([-1, 0, 1, 2, 0, 3])
filtered_array = array_a[array_a > 0]
print(filtered_array)

[1 2 3]


19.

In [24]:
y = numpy.array([[3, 2, 3], [5, 2, 8], [3, 5, 9]])
y_transpose = y.T
print(y_transpose)

[[3 5 3]
 [2 2 5]
 [3 8 9]]


20.

In [25]:
zero_array = numpy.zeros((2, 4))
print(zero_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


21.

In [26]:
zero_array = numpy.zeros((2, 4))
zero_array[:, 1] = 1
print(zero_array)

[[0. 1. 0. 0.]
 [0. 1. 0. 0.]]


22.

In [28]:
%reset -f

# Exrecise 2

### Chapter 3

1.

In [7]:
def my_sinh(x):
    y = (math.exp(x) - math.exp(-x)) / 2
    return y

x = 0
result = my_sinh(x)
print(f"sinh({x}) = {result}")
x = 1
result = my_sinh(x)
print(f"sinh({x}) = {result}")
x = 2
result = my_sinh(x)
print(f"sinh({x}) = {result}")


sinh(0) = 0.0
sinh(1) = 1.1752011936438014
sinh(2) = 3.626860407847019


2.

In [16]:

def my_checker_board(n):
    m = numpy.ones((n, n), dtype=int) 
    m[1::2, ::2] = 0  
    m[::2, 1::2] = 0  
    return m
n = 5
checkerboard = my_checker_board(n)
print(checkerboard)

[[1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]]


3.

In [23]:
def my_triangle(b, h):
    area = 0.5 * b * h
    return area
print(my_triangle(1, 1))
print(my_triangle(2, 1))
print(my_triangle(12, 5))


0.5
1.0
30.0


4.

5.

In [36]:
def my_cylinder(r, h):
    surface_area = 2 * math.pi * r**2 + 2 * math.pi * r * h
    volume = math.pi * r**2 * h 
    return [surface_area, volume]

result = my_cylinder(1, 5)
print(f"Surface area: {result[0]}")
print(f"Volume: {result[1]}")

Surface area: 37.69911184307752
Volume: 15.707963267948966


6.

In [55]:
def my_n_odds(a):
    numArray = numpy.array(a)
    odd_count = numpy.sum(numArray % 2 != 0)
    return odd_count
count = my_n_odds(numpy.arange(2, 100, 2))
print(f"Number of odd integers: {count}")

Number of odd integers: 0


7.

In [58]:
def add_string(s1, s2):
    result = s1 + s2
    return result
s1 = add_string('Programming', ' ')
s2 = add_string('is ', 'fun!')
print(add_string(s1, s2))

Programming is fun!


8.

In [61]:
def greeting(name, age):
    result = f"Hi, my name is {name} and I am {int(age)} years old."
    return result
name = "John"
age = 26
greet_message = greeting(name, age)
print(greet_message)

Hi, my name is John and I am 26 years old.


9.

In [68]:
def my_within_tolerance(A, a, tol):
    A = numpy.array(A)
    within_tolerance = numpy.abs(A - a) < tol
    print("Values within tolerance:")
    for value in A[within_tolerance]:
        print(value)

my_within_tolerance([0, 1, 2, 3], 1.5, 0.75)
my_within_tolerance(numpy.arange(0, 1.01, 0.01), 0.5, 0.03)

Values within tolerance:
1
2
Values within tolerance:
0.47000000000000003
0.48
0.49
0.5
0.51
0.52


10.

### Chapter 9

1.

In [3]:
def my_bin_2_dec(b):
    d = 0
    for i in range(len(b)):
        d += b[i] * (2 ** i)
    return d
print(my_bin_2_dec([1, 1, 1])) 


7
11
8
1
0


2.

In [4]:
def my_dec_2_bin(d):
    if d == 0:
        return [0]
    
    b = []
    while d > 0:
        b.append(d % 2)
        d = d // 2
    b.reverse()
    return b

print(my_dec_2_bin(0))
print(my_dec_2_bin(23))
print(my_dec_2_bin(2097)) 

[0]
[1, 0, 1, 1, 1]
[1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1]


3.

In [22]:
def my_bin_2_dec(b):
    d = 0
    for i in range(len(b)):
        d += b[i] * (2 ** i)
    return d

def my_dec_2_bin(d):
    if d == 0:
        return [0]
    
    b = []
    while d > 0:
        b.append(d % 2)
        d = d // 2
    b.reverse()
    return b


4.

In [25]:
def my_bin_adder(b1, b2):
    max_len = max(len(b1), len(b2))
    b1 = [0] * (max_len - len(b1)) + b1
    b2 = [0] * (max_len - len(b2)) + b2
    
    carry = 0
    result = []
    for bit1, bit2 in zip(reversed(b1), reversed(b2)):
        total = bit1 + bit2 + carry
        result_bit = total % 2
        carry = total // 2
        result.append(result_bit)
    
    if carry:
        result.append(carry)
    
    result.reverse()
    
    return result

print(my_bin_adder([1, 1, 1, 1,1] , [1])) 

[1, 0, 0, 0, 0, 0]


5.

In floating-point representation, bits are allocated across three components: the sign, the exponent (or characteristic), and the fraction (or mantissa). The distribution of bits among these components affects the precision and range of the floating-point numbers that can be represented.

6.

In [30]:
def my_ieee_2_dec(ieee):
    
    sign_bit = int(ieee[0])
    exponent_bits = ieee[1:12]
    fraction_bits = ieee[12:]
    
    exponent = int(exponent_bits, 2)
    fraction = int(fraction_bits, 2)
    
    bias = 1023
    
    if exponent == 0:
        if fraction == 0:
            return 0.0  
        exponent_actual = 1 - bias  
    elif exponent == 0x7FF:
        if fraction == 0:
            return (-1) ** sign_bit * float('inf')
        else:
            return float('nan') 
    else:
        exponent_actual = exponent - bias
    
    fraction_value = 0.0
    for i in range(52):
        if fraction & (1 << (51 - i)):
            fraction_value += 2 ** (-1 * (i + 1))
    
    decimal_value = (-1) ** sign_bit * 2 ** exponent_actual * (1 + fraction_value)
    
    return decimal_value

ieee = '1100000001001000000000000000000000000000000000000000000000000000' 
print(my_ieee_2_dec(ieee)) 


-48.0


7.

In [35]:
def my_dec_2_ieee(d):
    import struct
    
    if d == 0:
        return '0' * 64
    packed = struct.pack('>d', d)
    ieee_binary = ''.join(f'{byte:08b}' for byte in packed)
    
    return ieee_binary

8.

# Exrecise 3

### Chapter 16

2.

3.

In [39]:
import numpy as np

def my_func_fit(x, y):
    x = np.ravel(x)
    y = np.ravel(y)
    
    if np.any(x <= 0) or np.any(y <= 0):
        raise ValueError("x and y must be positive for log transformation.")

    X = np.log(x)
    Y = np.log(y)

    A = np.vstack([X, np.ones(len(X))]).T
    beta, log_alpha = np.linalg.lstsq(A, Y, rcond=None)[0]

    alpha = np.exp(log_alpha)
    
    return alpha, beta
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 8, 18, 32, 50])

4.

Total Error: Compute using SSE for the given data points and fitted polynomial.
Placing a New Point: Ensure it lies on the fitted polynomial to avoid adding error.

5.

### Chapter 17

1.

In [10]:
def my_lin_interp(x, y, X):
    Y = []

    for xi in X:
        for j in range(len(x) - 1):
            if x[j] <= xi <= x[j + 1]:
                y_interp = y[j] + (xi - x[j]) * (y[j + 1] - y[j]) / (x[j + 1] - x[j])
                Y.append(y_interp)
                break
        else:
            raise ValueError("X[i] is out of the bounds of x")
        
    return Y

2.

In [40]:
import numpy as np

def my_cubic_spline(x, y, X):
    n = len(x)
    h = np.diff(x)
    alpha = np.zeros(n-1)
    l = np.zeros(n)
    mu = np.zeros(n-1)
    z = np.zeros(n)
    
    for i in range(1, n-1):
        alpha[i] = (3/(h[i])) * (y[i+1] - y[i]) - (3/(h[i-1])) * (y[i] - y[i-1])
    
    l[0] = 1
    mu[0] = 0
    z[0] = 0
    
    for i in range(1, n-1):
        l[i] = 2 * (x[i+1] - x[i-1]) - h[i-1] * mu[i-1]
        mu[i] = h[i] / l[i]
        z[i] = (alpha[i] - h[i-1] * z[i-1]) / l[i]
    
    l[-1] = 1
    z[-1] = 0
    c = np.zeros(n)
    b = np.zeros(n-1)
    d = np.zeros(n-1)
    
    c[-1] = 0
    for j in range(n-2, -1, -1):
        c[j] = z[j] - mu[j] * c[j+1]
        b[j] = (y[j+1] - y[j]) / h[j] - h[j] * (c[j+1] + 2 * c[j]) / 3
        d[j] = (c[j+1] - c[j]) / (3 * h[j])
    
    Y = np.zeros(len(X))
    for k, xk in enumerate(X):
        i = np.searchsorted(x, xk) - 1
        if i < 0:
            i = 0
        elif i >= n-1:
            i = n-2
        
        dx = xk - x[i]
        Y[k] = y[i] + b[i] * dx + c[i] * dx**2 + d[i] * dx**3
    
    return Y

5.

6.

In [42]:
import numpy as np

def my_quintic_spline(x, y, X):
    n = len(x)
    h = np.diff(x)
    delta_y = np.diff(y)
    
    N = 6 * (n - 1)
    A = np.zeros((N, N))
    B = np.zeros(N)
    
    def index(i, j):
        return 6 * i + j
    
    for i in range(n - 1):
        A[index(i, 0), index(i, 0)] = 1
        A[index(i, 1), index(i, 1)] = h[i]
        A[index(i, 2), index(i, 2)] = h[i]**2
        A[index(i, 3), index(i, 3)] = h[i]**3
        A[index(i, 4), index(i, 4)] = h[i]**4
        A[index(i, 5), index(i, 5)] = h[i]**5
        
        if i < n - 2:
            A[index(i + 1, 0), index(i + 1, 0)] = 1
            A[index(i + 1, 1), index(i + 1, 1)] = 0
            A[index(i + 1, 2), index(i + 1, 2)] = 0
            A[index(i + 1, 3), index(i + 1, 3)] = 0
            A[index(i + 1, 4), index(i + 1, 4)] = 0
            A[index(i + 1, 5), index(i + 1, 5)] = 0
            
        B[index(i)] = y[i + 1] - y[i]

    A[0, 0] = 1
    A[-6, -6] = 1
    B[0] = 0
    B[-6] = 0

    coeffs = np.linalg.solve(A, B)
    
    a = coeffs[0::6]
    b = coeffs[1::6]
    c = coeffs[2::6]
    d = coeffs[3::6]
    e = coeffs[4::6]
    f = coeffs[5::6]
    
    Y = np.zeros(len(X))
    for k, xk in enumerate(X):
        i = np.searchsorted(x, xk) - 1
        if i < 0:
            i = 0
        elif i >= n-1:
            i = n-2
        
        dx = xk - x[i]
        Y[k] = (a[i] +
                b[i] * dx +
                c[i] * dx**2 +
                d[i] * dx**3 +
                e[i] * dx**4 +
                f[i] * dx**5)
    
    return Y

7.

### Chapter 19

1.

In [43]:
def my_nth_root(x, n, tol):
    r = x if x > 1 else 1.0
    
    while True:
        f_r = r**n - x
        f_prime_r = n * r**(n - 1)

        
        r_next = r - f_r / f_prime_r
        
    
        if abs(f_r) < tol:
            return r
        
        r = r_next

2.

3.

The bisection method fails for f(x)=1/x because the function is not continuous across intervals that include x=0 The discontinuity violates the requirement for the function to be continuous and for the method to guarantee a root within the interval.

4.

5.

In [46]:
import numpy as np

def my_newton(f, df, x0, tol):
    R = [x0]
    E = [abs(f(x0))]
    
    while E[-1] >= tol:
        x_current = R[-1]

        x_next = x_current - f(x_current) / df(x_current)
        
        error_next = abs(f(x_next))
        
        R.append(x_next)
        E.append(error_next)

    R = np.array(R)
    E = np.array(E)
    
    return R, E

f = lambda x: x**2 - 2
df = lambda x: 2*x
[R, E] = my_newton(f, df, 1, 1e-5)
print(R,E)

[1.         1.5        1.41666667 1.41421569] [1.00000000e+00 2.50000000e-01 6.94444444e-03 6.00730488e-06]


6.